# Use a lightweight NGINX image as the base
FROM nginx:alpine

# Copy the client application files into the NGINX web server directory
COPY . /usr/share/nginx/html

# Expose port 80 (the default NGINX port)
EXPOSE 80